name: david_terceiro
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true  
  ios: false     
  image_path: "assets/banana-icon.jpg"  

flutter:
  assets:
     - assets/banana-icon.jpg
     - assets/banana-logo.jpg

  uses-material-design: true