// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByEFjA4ByGRKBg6Y5yY7E5NtMBiWmw7pw',
    appId: '1:296060200918:web:c987ae98762db89d3c2677',
    messagingSenderId: '296060200918',
    projectId: 'david-terceiro',
    authDomain: 'david-terceiro.firebaseapp.com',
    storageBucket: 'david-terceiro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfaCmhbYGLu20OZEI5wJkSiRRrhtHnty0',
    appId: '1:296060200918:android:34dd979a3680be063c2677',
    messagingSenderId: '296060200918',
    projectId: 'david-terceiro',
    storageBucket: 'david-terceiro.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByEFjA4ByGRKBg6Y5yY7E5NtMBiWmw7pw',
    appId: '1:296060200918:web:cc4582f200b16e643c2677',
    messagingSenderId: '296060200918',
    projectId: 'david-terceiro',
    authDomain: 'david-terceiro.firebaseapp.com',
    storageBucket: 'david-terceiro.firebasestorage.app',
  );

}